### ISSUE TITLE
Debian 11 - kernel: 5.10.0-32-amd64 - Salvium v0.5.2 - Impossible to build from the sources: rror: ‘virtual std::vector<long unsigned int>

### ISSUE THREAD

**Issue by blackmennewstyle** [salvium/salvium#7]
Hello beautiful dev(s),

Your XMR fork source code does not build on Debian 11 - kernel: 5.10.0-32-amd64 - Salvium v0.5.2:
```[ 78%] Built target block_fuzz_tests
In file included from /home/ceedii/salvium/tests/block_weight/block_weight.cpp:36:
/home/ceedii/salvium/src/blockchain_db/testdb.h:79:33: error: ‘virtual std::vector<long unsigned int> cryptonote::BaseTestDB::get_block_cumulative_rct_outputs(const std::vector<long unsigned int>&) const’ marked ‘override’, but does not override
   79 |   virtual std::vector<uint64_t> get_block_cumulative_rct_outputs(const std::vector<uint64_t> &heights) const override { return {}; }
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ceedii/salvium/src/blockchain_db/testdb.h:111:46: error: invalid covariant return type for ‘virtual std::vector<std::vector<long unsigned int> > cryptonote::BaseTestDB::get_tx_amount_output_indices(uint64_t, size_t) const’
  111 |   virtual std::vector<std::vector<uint64_t>> get_tx_amount_output_indices(const uint64_t tx_index, size_t n_txes) const override { return std::vector<std::vector<uint64_t>>(); }
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/ceedii/salvium/src/rpc/core_rpc_server_commands_defs.h:36,
                 from /home/ceedii/salvium/src/cryptonote_core/blockchain.h:57,
                 from /home/ceedii/salvium/tests/block_weight/block_weight.cpp:33:
/home/ceedii/salvium/src/blockchain_db/blockchain_db.h:1585:67: note: overridden function is ‘virtual std::vector<std::vector<std::pair<long unsigned int, long unsigned int> > > cryptonote::BlockchainDB::get_tx_amount_output_indices(uint64_t, size_t) const’
 1585 |   virtual std::vector<std::vector<std::pair<uint64_t, uint64_t>>> get_tx_amount_output_indices(const uint64_t tx_id, size_t n_txes = 1) const = 0;
      |                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/ceedii/salvium/tests/block_weight/block_weight.cpp:36:
/home/ceedii/salvium/src/blockchain_db/testdb.h:114:20: error: ‘virtual uint64_t cryptonote::BaseTestDB::add_transaction_data(const crypto::hash&, const std::pair<cryptonote::transaction, boost::basic_string_ref<char, std::char_traits<char> > >&, const crypto::hash&, const crypto::hash&)’ marked ‘override’, but does not override
  114 |   virtual uint64_t add_transaction_data(const crypto::hash& blk_hash, const std::pair<cryptonote::transaction, cryptonote::blobdata_ref>& tx, const crypto::hash& tx_hash, const crypto::hash& tx_prunable_hash) override {return 0;}
      |                    ^~~~~~~~~~~~~~~~~~~~
/home/ceedii/salvium/src/blockchain_db/testdb.h:115:16: error: ‘virtual void cryptonote::BaseTestDB::remove_transaction_data(const crypto::hash&, const cryptonote::transaction&)’ marked ‘override’, but does not override
  115 |   virtual void remove_transaction_data(const crypto::hash& tx_hash, const cryptonote::transaction& tx) override {}
      |                ^~~~~~~~~~~~~~~~~~~~~~~
/home/ceedii/salvium/src/blockchain_db/testdb.h:116:20: error: conflicting return type specified for ‘virtual uint64_t cryptonote::BaseTestDB::add_output(const crypto::hash&, const cryptonote::tx_out&, const uint64_t&, uint64_t, const rct::key*)’
  116 |   virtual uint64_t add_output(const crypto::hash& tx_hash, const cryptonote::tx_out& tx_output, const uint64_t& local_index, const uint64_t unlock_time, const rct::key *commitment) override {return 0;}
      |                    ^~~~~~~~~~
In file included from /home/ceedii/salvium/src/rpc/core_rpc_server_commands_defs.h:36,
                 from /home/ceedii/salvium/src/cryptonote_core/blockchain.h:57,
                 from /home/ceedii/salvium/tests/block_weight/block_weight.cpp:33:
/home/ceedii/salvium/src/blockchain_db/blockchain_db.h:515:41: note: overridden function is ‘virtual std::pair<long unsigned int, long unsigned int> cryptonote::BlockchainDB::add_output(const crypto::hash&, const cryptonote::tx_out&, const uint64_t&, uint64_t, const rct::key*)’
  515 |   virtual std::pair<uint64_t, uint64_t> add_output(const crypto::hash& tx_hash, const tx_out& tx_output, const uint64_t& local_index, const uint64_t unlock_time, const rct::key *commitment) = 0;
      |                                         ^~~~~~~~~~
In file included from /home/ceedii/salvium/tests/block_weight/block_weight.cpp:36:
/home/ceedii/salvium/src/blockchain_db/testdb.h:117:16: error: ‘virtual void cryptonote::BaseTestDB::add_tx_amount_output_indices(uint64_t, const std::vector<long unsigned int>&)’ marked ‘override’, but does not override
  117 |   virtual void add_tx_amount_output_indices(const uint64_t tx_index, const std::vector<uint64_t>& amount_output_indices) override {}
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ceedii/salvium/src/blockchain_db/testdb.h:141:16: error: ‘virtual void cryptonote::BaseTestDB::add_block(const cryptonote::block&, size_t, uint64_t, const difficulty_type&, const uint64_t&, uint64_t, const crypto::hash&)’ marked ‘override’, but does not override
  141 |   virtual void add_block( const cryptonote::block& blk
      |                ^~~~~~~~~
/home/ceedii/salvium/tests/block_weight/block_weight.cpp:62:16: error: ‘virtual void {anonymous}::TestDB::add_block(const cryptonote::block&, size_t, uint64_t, const difficulty_type&, const uint64_t&, uint64_t, oracle::asset_type_counts&, const crypto::hash&)’ marked ‘override’, but does not override
   62 |   virtual void add_block( const cryptonote::block& blk
      |                ^~~~~~~~~
/home/ceedii/salvium/tests/block_weight/block_weight.cpp: In function ‘void test(test_t, uint64_t)’:
/home/ceedii/salvium/tests/block_weight/block_weight.cpp:115:40: error: ‘cryptonote::tx_memory_pool::tx_memory_pool(cryptonote::Blockchain&)’ is private within this context
  115 |   cryptonote::tx_memory_pool txpool(*bc); \
      |                                        ^
/home/ceedii/salvium/tests/block_weight/block_weight.cpp:133:28: note: in expansion of macro ‘PREFIX_WINDOW’
  133 | #define PREFIX(hf_version) PREFIX_WINDOW(hf_version, LONG_TERM_BLOCK_WEIGHT_WINDOW)
      |                            ^~~~~~~~~~~~~
/home/ceedii/salvium/tests/block_weight/block_weight.cpp:145:3: note: in expansion of macro ‘PREFIX’
  145 |   PREFIX(10);
      |   ^~~~~~
In file included from /home/ceedii/salvium/tests/block_weight/block_weight.cpp:34:
/home/ceedii/salvium/src/cryptonote_core/tx_pool.h:493:5: note: declared private here
  493 |     tx_memory_pool(Blockchain& bchs);
      |     ^~~~~~~~~~~~~~
/home/ceedii/salvium/tests/block_weight/block_weight.cpp:126:40: error: invalid new-expression of abstract class type ‘{anonymous}::TestDB’
  126 |   bool r = blockchain->init(new TestDB(), cryptonote::FAKECHAIN, true, &opts.test_options, 0, NULL); \
      |                                        ^
/home/ceedii/salvium/tests/block_weight/block_weight.cpp:133:28: note: in expansion of macro ‘PREFIX_WINDOW’
  133 | #define PREFIX(hf_version) PREFIX_WINDOW(hf_version, LONG_TERM_BLOCK_WEIGHT_WINDOW)
      |                            ^~~~~~~~~~~~~
/home/ceedii/salvium/tests/block_weight/block_weight.cpp:145:3: note: in expansion of macro ‘PREFIX’
  145 |   PREFIX(10);
      |   ^~~~~~
/home/ceedii/salvium/tests/block_weight/block_weight.cpp:50:7: note:   because the following virtual functions are pure within ‘{anonymous}::TestDB’:
   50 | class TestDB: public cryptonote::BaseTestDB
      |       ^~~~~~
In file included from /home/ceedii/salvium/src/rpc/core_rpc_server_commands_defs.h:36,
                 from /home/ceedii/salvium/src/cryptonote_core/blockchain.h:57,
                 from /home/ceedii/salvium/tests/block_weight/block_weight.cpp:33:
/home/ceedii/salvium/src/blockchain_db/blockchain_db.h:423:16: note:     ‘virtual void cryptonote::BlockchainDB::add_block(const cryptonote::block&, size_t, uint64_t, const difficulty_type&, const uint64_t&, uint64_t, oracle::asset_type_counts&, const crypto::hash&, uint64_t, uint64_t, const cryptonote::network_type&, cryptonote::yield_block_info&)’
  423 |   virtual void add_block( const block& blk,
      |                ^~~~~~~~~
/home/ceedii/salvium/src/blockchain_db/blockchain_db.h:469:20: note:     ‘virtual uint64_t cryptonote::BlockchainDB::add_transaction_data(const crypto::hash&, const std::pair<cryptonote::transaction, boost::basic_string_ref<char, std::char_traits<char> > >&, const crypto::hash&, const crypto::hash&, bool)’
  469 |   virtual uint64_t add_transaction_data(const crypto::hash& blk_hash, const std::pair<transaction, blobdata_ref>& tx, const crypto::hash& tx_hash, const crypto::hash& tx_prunable_hash, const bool miner_tx) = 0;
      |                    ^~~~~~~~~~~~~~~~~~~~
/home/ceedii/salvium/src/blockchain_db/blockchain_db.h:487:16: note:     ‘virtual void cryptonote::BlockchainDB::remove_transaction_data(const crypto::hash&, const cryptonote::transaction&, bool)’
  487 |   virtual void remove_transaction_data(const crypto::hash& tx_hash, const transaction& tx, const bool miner_tx) = 0;
      |                ^~~~~~~~~~~~~~~~~~~~~~~
/home/ceedii/salvium/src/blockchain_db/blockchain_db.h:530:16: note:     ‘virtual void cryptonote::BlockchainDB::add_tx_amount_output_indices(uint64_t, const std::vector<std::pair<long unsigned int, long unsigned int> >&)’
  530 |   virtual void add_tx_amount_output_indices(const uint64_t tx_id, const std::vector<std::pair<uint64_t, uint64_t>>& amount_output_indices) = 0;
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ceedii/salvium/src/blockchain_db/blockchain_db.h:1006:54: note:     ‘virtual std::pair<std::vector<long unsigned int>, long unsigned int> cryptonote::BlockchainDB::get_block_cumulative_rct_outputs(const std::vector<long unsigned int>&, std::string) const’
 1006 |   virtual std::pair<std::vector<uint64_t>, uint64_t> get_block_cumulative_rct_outputs(const std::vector<uint64_t> &heights, const std::string asset_type) const = 0;
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ceedii/salvium/src/blockchain_db/blockchain_db.h:1198:43: note:     ‘virtual std::map<std::__cxx11::basic_string<char>, long unsigned int> cryptonote::BlockchainDB::get_circulating_supply() const’
 1198 |   virtual std::map<std::string, uint64_t> get_circulating_supply() const = 0;
      |                                           ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/ceedii/salvium/src/rpc/core_rpc_server_commands_defs.h:36,
                 from /home/ceedii/salvium/src/cryptonote_core/blockchain.h:57,
                 from /home/ceedii/salvium/tests/block_weight/block_weight.cpp:33:
/home/ceedii/salvium/src/blockchain_db/blockchain_db.h:1462:20: note:     ‘virtual uint64_t cryptonote::BlockchainDB::get_num_outputs_of_asset_type(std::string) const’
 1462 |   virtual uint64_t get_num_outputs_of_asset_type(const std::string asset_type) const = 0;
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ceedii/salvium/src/blockchain_db/blockchain_db.h:1499:16: note:     ‘virtual void cryptonote::BlockchainDB::get_output_id_from_asset_type_output_index(std::string, const std::vector<long unsigned int>&, std::vector<long unsigned int>&) const’
 1499 |   virtual void get_output_id_from_asset_type_output_index(const std::string asset_type, const std::vector<uint64_t> &asset_type_output_indices, std::vector<uint64_t> &output_indices) const = 0;
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ceedii/salvium/src/blockchain_db/blockchain_db.h:1510:20: note:     ‘virtual uint64_t cryptonote::BlockchainDB::get_output_id_from_asset_type_output_index(std::string, const uint64_t&) const’
 1510 |   virtual uint64_t get_output_id_from_asset_type_output_index(const std::string asset_type, const uint64_t &asset_type_output_index) const = 0;
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ceedii/salvium/src/blockchain_db/blockchain_db.h:1918:15: note:     ‘virtual int cryptonote::BlockchainDB::get_yield_block_info(uint64_t, cryptonote::yield_block_info&) const’
 1918 |   virtual int get_yield_block_info(const uint64_t height, yield_block_info& ybi) const = 0;
      |               ^~~~~~~~~~~~~~~~~~~~
/home/ceedii/salvium/src/blockchain_db/blockchain_db.h:1919:15: note:     ‘virtual int cryptonote::BlockchainDB::get_yield_tx_info(uint64_t, std::vector<cryptonote::yield_tx_info>&) const’
 1919 |   virtual int get_yield_tx_info(const uint64_t height, std::vector<yield_tx_info>& yti_container) const = 0;
      |               ^~~~~~~~~~~~~~~~~
/home/ceedii/salvium/tests/block_weight/block_weight.cpp:152:115: error: no matching function for call to ‘cryptonote::BlockchainDB::add_block(std::pair<cryptonote::block, const char*>, int, int, uint64_t, uint64_t, <brace-enclosed initializer list>)’
  152 |     bc->get_db().add_block(std::make_pair(b, ""), 300000, 300000, bc->get_db().height(), bc->get_db().height(), {});
      |                                                                                                                   ^
In file included from /home/ceedii/salvium/src/rpc/core_rpc_server_commands_defs.h:36,
                 from /home/ceedii/salvium/src/cryptonote_core/blockchain.h:57,
                 from /home/ceedii/salvium/tests/block_weight/block_weight.cpp:33:
/home/ceedii/salvium/src/blockchain_db/blockchain_db.h:423:16: note: candidate: ‘virtual void cryptonote::BlockchainDB::add_block(const cryptonote::block&, size_t, uint64_t, const difficulty_type&, const uint64_t&, uint64_t, oracle::asset_type_counts&, const crypto::hash&, uint64_t, uint64_t, const cryptonote::network_type&, cryptonote::yield_block_info&)’
  423 |   virtual void add_block( const block& blk,
      |                ^~~~~~~~~
/home/ceedii/salvium/src/blockchain_db/blockchain_db.h:423:16: note:   candidate expects 12 arguments, 6 provided
/home/ceedii/salvium/src/blockchain_db/blockchain_db.h:881:20: note: candidate: ‘virtual uint64_t cryptonote::BlockchainDB::add_block(const std::pair<cryptonote::block, std::__cxx11::basic_string<char> >&, size_t, uint64_t, const difficulty_type&, const uint64_t&, const std::vector<std::pair<cryptonote::transaction, std::__cxx11::basic_string<char> > >&, const cryptonote::network_type&, cryptonote::yield_block_info&)’
  881 |   virtual uint64_t add_block( const std::pair<block, blobdata>& blk
      |                    ^~~~~~~~~
/home/ceedii/salvium/src/blockchain_db/blockchain_db.h:881:20: note:   candidate expects 8 arguments, 6 provided
/home/ceedii/salvium/tests/block_weight/block_weight.cpp:186:118: error: no matching function for call to ‘cryptonote::BlockchainDB::add_block(std::pair<cryptonote::block, const char*>, uint64_t&, uint64_t&, uint64_t, uint64_t, <brace-enclosed initializer list>)’
  186 |     bc->get_db().add_block(std::make_pair(std::move(b), ""), w, ltw, bc->get_db().height(), bc->get_db().height(), {});
      |                                                                                                                      ^
In file included from /home/ceedii/salvium/src/rpc/core_rpc_server_commands_defs.h:36,
                 from /home/ceedii/salvium/src/cryptonote_core/blockchain.h:57,
                 from /home/ceedii/salvium/tests/block_weight/block_weight.cpp:33:
/home/ceedii/salvium/src/blockchain_db/blockchain_db.h:423:16: note: candidate: ‘virtual void cryptonote::BlockchainDB::add_block(const cryptonote::block&, size_t, uint64_t, const difficulty_type&, const uint64_t&, uint64_t, oracle::asset_type_counts&, const crypto::hash&, uint64_t, uint64_t, const cryptonote::network_type&, cryptonote::yield_block_info&)’
  423 |   virtual void add_block( const block& blk,
      |                ^~~~~~~~~
/home/ceedii/salvium/src/blockchain_db/blockchain_db.h:423:16: note:   candidate expects 12 arguments, 6 provided
/home/ceedii/salvium/src/blockchain_db/blockchain_db.h:881:20: note: candidate: ‘virtual uint64_t cryptonote::BlockchainDB::add_block(const std::pair<cryptonote::block, std::__cxx11::basic_string<char> >&, size_t, uint64_t, const difficulty_type&, const uint64_t&, const std::vector<std::pair<cryptonote::transaction, std::__cxx11::basic_string<char> > >&, const cryptonote::network_type&, cryptonote::yield_block_info&)’
  881 |   virtual uint64_t add_block( const std::pair<block, blobdata>& blk
      |                    ^~~~~~~~~
/home/ceedii/salvium/src/blockchain_db/blockchain_db.h:881:20: note:   candidate expects 8 arguments, 6 provided
make[3]: *** [tests/block_weight/CMakeFiles/block_weight.dir/build.make:82: tests/block_weight/CMakeFiles/block_weight.dir/block_weight.cpp.o] Error 1
make[3]: Leaving directory '/home/ceedii/salvium/build/Linux/_HEAD_detached_at_v0.5.2_/release'
make[2]: *** [CMakeFiles/Makefile2:5895: tests/block_weight/CMakeFiles/block_weight.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
/home/ceedii/salvium/src/rpc/core_rpc_server.cpp: In member function ‘bool cryptonote::core_rpc_server::on_get_base_fee_estimate(const request&, cryptonote::COMMAND_RPC_GET_BASE_FEE_ESTIMATE::response&, epee::json_rpc::error&, const connection_context*)’:
/home/ceedii/salvium/src/rpc/core_rpc_server.cpp:3061:19: warning: unused variable ‘version’ [-Wunused-variable]
 3061 |     const uint8_t version = m_core.get_blockchain_storage().get_current_hard_fork_version();
      |                   ^~~~~~~
/home/ceedii/salvium/src/rpc/core_rpc_server.cpp: In member function ‘bool cryptonote::core_rpc_server::on_rpc_access_data(const request&, cryptonote::COMMAND_RPC_ACCESS_DATA::response&, epee::json_rpc::error&, const connection_context*)’:
/home/ceedii/salvium/src/rpc/core_rpc_server.cpp:3711:14: warning: ‘r’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 3711 |       return r;
      |              ^
/home/ceedii/salvium/src/rpc/core_rpc_server.cpp: In member function ‘bool cryptonote::core_rpc_server::on_get_limit(const request&, cryptonote::COMMAND_RPC_GET_LIMIT::response&, const connection_context*)’:
/home/ceedii/salvium/src/rpc/core_rpc_server.cpp:3107:14: warning: ‘r’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 3107 |       return r;
      |              ^
/home/ceedii/salvium/src/rpc/core_rpc_server.cpp: In member function ‘bool cryptonote::core_rpc_server::on_get_version(const request&, cryptonote::COMMAND_RPC_GET_VERSION::response&, epee::json_rpc::error&, const connection_context*)’:
/home/ceedii/salvium/src/rpc/core_rpc_server.cpp:2956:14: warning: ‘r’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 2956 |       return r;
      |              ^
/home/ceedii/salvium/src/rpc/core_rpc_server.cpp: In member function ‘bool cryptonote::core_rpc_server::on_get_height(const request&, cryptonote::COMMAND_RPC_GET_HEIGHT::response&, const connection_context*)’:
/home/ceedii/salvium/src/rpc/core_rpc_server.cpp:464:14: warning: ‘r’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  464 |       return r;
      |              ^
make[3]: Leaving directory '/home/ceedii/salvium/build/Linux/_HEAD_detached_at_v0.5.2_/release'
[ 78%] Built target obj_rpc
[ 78%] Linking CXX executable net_load_tests_srv
make[3]: Leaving directory '/home/ceedii/salvium/build/Linux/_HEAD_detached_at_v0.5.2_/release'
[ 78%] Built target net_load_tests_srv
[ 78%] Linking CXX executable net_load_tests_clt
make[3]: Leaving directory '/home/ceedii/salvium/build/Linux/_HEAD_detached_at_v0.5.2_/release'
[ 78%] Built target net_load_tests_clt
/home/ceedii/salvium/src/wallet/wallet2.cpp: In member function ‘void tools::wallet2::refresh(bool, uint64_t, uint64_t&, bool&, bool, bool, uint64_t)’:
/home/ceedii/salvium/src/wallet/wallet2.cpp:4395:8: warning: unused variable ‘refreshed’ [-Wunused-variable]
 4395 |   bool refreshed = false;
      |        ^~~~~~~~~
/home/ceedii/salvium/src/wallet/wallet2.cpp: In member function ‘std::map<unsigned int, std::pair<long unsigned int, std::pair<long unsigned int, long unsigned int> > > tools::wallet2::unlocked_balance_per_subaddress(uint32_t, const string&, bool)’:
/home/ceedii/salvium/src/wallet/wallet2.cpp:7044:18: warning: unused variable ‘now’ [-Wunused-variable]
 7044 |   const uint64_t now = time(NULL);
      |                  ^~~
/home/ceedii/salvium/src/wallet/wallet2.cpp: In member function ‘void tools::wallet2::get_outs(std::vector<std::vector<std::tuple<long unsigned int, crypto::public_key, rct::key> > >&, const std::vector<long unsigned int>&, size_t, std::vector<long unsigned int>&, std::unordered_set<crypto::public_key>&, uint64_t&, uint64_t&)’:
/home/ceedii/salvium/src/wallet/wallet2.cpp:9632:16: warning: variable ‘num_outs’ set but not used [-Wunused-but-set-variable]
 9632 |       uint64_t num_outs = 0;
      |                ^~~~~~~~
/home/ceedii/salvium/src/wallet/wallet2.cpp: In member function ‘std::vector<long unsigned int> tools::wallet2::pick_preferred_rct_inputs(uint64_t, uint32_t, const std::set<unsigned int>&, const string&)’:
/home/ceedii/salvium/src/wallet/wallet2.cpp:10345:12: warning: unused variable ‘idx’ [-Wunused-variable]
10345 |     size_t idx = m_transfers_indices[asset_type][i];
      |            ^~~
/home/ceedii/salvium/src/wallet/wallet2.cpp: In member function ‘std::vector<tools::wallet2::pending_tx> tools::wallet2::create_transactions_2(std::vector<cryptonote::tx_destination_entry>, const string&, const string&, cryptonote::transaction_type, size_t, uint64_t, uint32_t, const std::vector<unsigned char>&, uint32_t, std::set<unsigned int>, const unique_index_container&)’:
/home/ceedii/salvium/src/wallet/wallet2.cpp:10605:18: warning: unused variable ‘current_height’ [-Wunused-variable]
10605 |   const uint64_t current_height = get_blockchain_current_height()-1;
      |                  ^~~~~~~~~~~~~~
/home/ceedii/salvium/src/wallet/wallet2.cpp:10606:12: warning: unused variable ‘hf_version’ [-Wunused-variable]
10606 |   uint32_t hf_version = get_current_hard_fork();
      |            ^~~~~~~~~~
/home/ceedii/salvium/src/wallet/wallet2.cpp:10611:8: warning: unused variable ‘b’ [-Wunused-variable]
10611 |   bool b = false;
      |        ^
/home/ceedii/salvium/src/wallet/wallet2.cpp: In member function ‘std::vector<tools::wallet2::pending_tx> tools::wallet2::create_transactions_all(uint64_t, cryptonote::transaction_type, const string&, const cryptonote::account_public_address&, bool, size_t, size_t, uint64_t, uint32_t, const std::vector<unsigned char>&, uint32_t, std::set<unsigned int>)’:
/home/ceedii/salvium/src/wallet/wallet2.cpp:11285:24: warning: unused variable ‘rct_config’ [-Wunused-variable]
11285 |   const rct::RCTConfig rct_config { rct::RangeProofPaddedBulletproof, 4 };
      |                        ^~~~~~~~~~
In file included from /usr/include/string.h:495,
                 from /usr/include/boost/range/detail/implementation_help.hpp:18,
                 from /usr/include/boost/range/end.hpp:20,
                 from /usr/include/boost/range/functions.hpp:19,
                 from /usr/include/boost/range/iterator_range_core.hpp:38,
                 from /usr/include/boost/range/iterator_range.hpp:13,
                 from /usr/include/boost/range/as_literal.hpp:18,
                 from /usr/include/boost/algorithm/string/classification.hpp:17,
                 from /home/ceedii/salvium/src/wallet/wallet2.cpp:39:
In function ‘char* strncpy(char*, const char*, size_t)’,
    inlined from ‘std::vector<tools::wallet2::pending_tx> tools::wallet2::create_transactions_return(std::vector<long unsigned int>)’ at /home/ceedii/salvium/src/wallet/wallet2.cpp:11398:15:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:34: warning: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ output truncated before terminating nul copying 6 bytes from a string of the same length [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: Leaving directory '/home/ceedii/salvium/build/Linux/_HEAD_detached_at_v0.5.2_/release'
[ 78%] Built target obj_wallet
[ 79%] Linking CXX executable core_proxy
make[3]: Leaving directory '/home/ceedii/salvium/build/Linux/_HEAD_detached_at_v0.5.2_/release'
[ 79%] Built target core_proxy
make[2]: Leaving directory '/home/ceedii/salvium/build/Linux/_HEAD_detached_at_v0.5.2_/release'
make[1]: *** [Makefile:160: all] Error 2
make[1]: Leaving directory '/home/ceedii/salvium/build/Linux/_HEAD_detached_at_v0.5.2_/release'
make: *** [Makefile:103: release-all] Error 2
```

:'(

**Comment by somerandomcryptoguy** [comment]
There were some issues with the various Monero tests compiling - building without the tests should have worked.

The upcoming `one` development has fully working test code as well, but it is not ready for production use at this time.
